import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import usersRouter from "./users";
import inquiriesRouter from "./inquiries";
import patientsRouter from "./patients";
import activitiesRouter from "./activities";
import reportsRouter from "./reports";
import settingsRouter from "./settings";
import referralsRouter from "./referrals";
import pipelineRouter from "./pipeline";
import analyticsRouter from "./analytics";
import aiRouter from "./ai";
import webhooksRouter from "./webhooks";
import bdRouter from "./bd";
import bdReportsRouter from "./bdReports";
import auditLogsRouter from "./auditLogs";
import bedsRouter from "./beds";

const router: IRouter = Router();

router.use(webhooksRouter);
router.use(healthRouter);
router.use(authRouter);
router.use(usersRouter);
router.use(inquiriesRouter);
router.use(patientsRouter);
router.use(activitiesRouter);
router.use(reportsRouter);
router.use(settingsRouter);
router.use(referralsRouter);
router.use(pipelineRouter);
router.use(analyticsRouter);
router.use(aiRouter);
router.use(bdRouter);
router.use(bdReportsRouter);
router.use(auditLogsRouter);
router.use(bedsRouter);

export default router;
